import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Products from '../../components/Products'
import Clients from '../../components/Clients'
import logo from '../../public/img/logo.png';
import { GetServerSideProps, GetStaticProps } from 'next';
const inter = Inter({ subsets: ['latin'] })
interface productsProps {
  data: {
    id: number,
    nombre: string,
    escripcion: string,
    precio: number,
  }[];
}

export default function Home({ data }: productsProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ display: 'flex', width: '100%'}}>
          <nav>
            <div >
              <Image src={logo} alt="logo" />
            </div>
            <div style={{ marginTop: '100px' }}>
              <div>
                <a >Productos</a>
              </div>
              <div>
                <a >Clientes</a>
              </div>
              <div>
                <a >Ventas</a>
              </div>
            </div>
            <div style={{ marginTop: '100px' }}>
              <a href="">Estadisticas</a>
            </div>
            <div style={{ marginTop: '95%' }}>
              footer
            </div>
          </nav>
          <div style={{ width: '100%', display: 'flex', flexDirection: "column", justifyContent:"center", marginLeft: '25%', marginRight: '5%'}}>
            <h1>Productos</h1>
            <Products />
            <Clients/>
          </div>
        </div>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('http://localhost:5086/api/Products')
  const data = await res.json()
  return {
    props: { data },
    revalidate: 1 // Regenera la página cada segundo
  }
}