import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Products from '../../components/Products'
import Clients from '../../components/Clients'
import logo from '../../public/img/petshopLogo.png';
import { useEffect, useState } from 'react'

export default function Home() {

  //States navbars
  const [products, setProducts] = useState(false);
  const [clients, setClients] = useState(false);
  const [options, setOptions] = useState( {
    products: false,
    clients: false,
    estadisticas: false,

  } );

  //hadler navbar
  const hadlerProducts = () => {
    setProducts(true);
    setClients(false);
  }
  const hadlerClients = () => {
    setClients(true);
    setProducts(false);
  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ display: 'flex', width: '100%'}}>
          <nav>
            <div >
              
              <center><Image src={logo} alt="logo" /></center>
            </div>
            <div style={{ marginTop: '100px' }}>
              <div  className={products ? "selectedDiv": ""} >
                <a onClick={()=> hadlerProducts()} >Productos</a>
              </div>
              <div  className={clients ? "selectedDiv": ""} > 
                <a  onClick={()=>hadlerClients()} >Clientes</a>
              </div>
              <div>
                <a >Ventas</a>
              </div>
            </div>
            <div style={{ marginTop: '100px' }}>
              <a href="">Estadisticas</a>
            </div>
            <div style={{ marginTop: '95%' }}>
              footer
            </div>
          </nav>
          <div style={{ width: '100%', display: 'flex', flexDirection: "column", justifyContent:"center", marginLeft: '25%', marginRight: '5%'}}>
            
            {products && <Products />}
            {clients && <Clients />}
          </div>
        </div>
      </main>
    </>
  )
}

